### ISSUE TITLE
read/write latency

### ISSUE THREAD

**Issue by erickga** [jasonmayes/Tessel-Multibox-Pointer#1]
I have settled the 1GB Ram_disk option and my latency time at the begging of the program is around 50ms and several minutes after it goes up to 120-150ms 

How can I reduce it to 15ms as you suggested ¿? 

*Never mind, JIMP was the problem

**Comment by jasonmayes** [comment]
Is this from client -> server or just for the disk write on the server? 

Oh it seems you have solved it. I shall close this. :-)
